default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: dbpass
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: apex-legends-randomizer_development

test:
  <<: *default
  database: apex-legends-randomizer_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: apex-legends-randomizer_production
  username: apex-legends-randomizer
  password: <%= ENV['APEX-LEGENDS-RANDOMIZER_DATABASE_PASSWORD'] %>
