WeaponCategory.create(name: 'アサルトライフル')
WeaponCategory.create(name: 'サブマシンガン')
WeaponCategory.create(name: 'ライトマシンガン')
WeaponCategory.create(name: 'マークスマン')
WeaponCategory.create(name: 'スナイパーライフル')
WeaponCategory.create(name: 'ショットガン')
WeaponCategory.create(name: 'ピストル')

Ammo.create(name: 'ライトアモ', image: 'light_ammos.png')
Ammo.create(name: 'ヘビーアモ', image: 'heavy_ammos.png')
Ammo.create(name: 'エネルギーアモ', image: 'energy_ammos.png')
Ammo.create(name: 'スナイパーアモ', image: 'sniper_ammos.png')
Ammo.create(name: 'ショットガンアモ', image: 'shotgun_ammos.png')
Ammo.create(name: 'アロー', image: 'arrows.png')

Weapon.create(name: 'R-301カービン', image: 'r-301.png', weapon_category_id: 1, ammo_id: 1)
Weapon.create(name: 'VK-47フラットライン', image: 'flatline.png', weapon_category_id: 1, ammo_id: 2)
Weapon.create(name: 'ヘムロックバーストAR', image: 'hemlok.png', weapon_category_id: 1, ammo_id: 2)
Weapon.create(name: 'ハボックライフル', image: 'havoc.png', weapon_category_id: 1, ammo_id: 3)
Weapon.create(name: 'オルタネーターSMG', image: 'alternator.png', weapon_category_id: 2, ammo_id: 1)
Weapon.create(name: 'R-99 SMG', image: 'r-99.png', weapon_category_id: 2, ammo_id: 1)
Weapon.create(name: 'C.A.R. SMG', image: 'car.png', weapon_category_id: 2, ammo_id: 2)
Weapon.create(name: 'プラウラーバーストPDW', image: 'prowler.png', weapon_category_id: 2, ammo_id: 2)
Weapon.create(name: 'ボルトSMG', image: 'volt.png', weapon_category_id: 2, ammo_id: 3)
Weapon.create(name: 'M600スピットファイア', image: 'spitfire.png', weapon_category_id: 3, ammo_id: 2)
Weapon.create(name: 'ランページLMG', image: 'rampage.png', weapon_category_id: 3, ammo_id: 2)
Weapon.create(name: 'ディヴォーションLMG', image: 'devotion.png', weapon_category_id: 3, ammo_id: 3)
Weapon.create(name: 'L-スターEMG', image: 'l-star.png', weapon_category_id: 3, ammo_id: 3)
Weapon.create(name: 'G7スカウト', image: 'g7_scout.png', weapon_category_id: 4, ammo_id: 1)
Weapon.create(name: '30-30リピーター', image: '30-30.png', weapon_category_id: 4, ammo_id: 2)
Weapon.create(name: 'トリプルテイク', image: 'triple_take.png', weapon_category_id: 4, ammo_id: 3)
Weapon.create(name: 'ボセックコンパウンドボウ', image: 'bocek.png', weapon_category_id: 4, ammo_id: 6)
Weapon.create(name: 'チャージライフル', image: 'charge_rifle.png', weapon_category_id: 5, ammo_id: 4)
Weapon.create(name: 'ロングボウDMR', image: 'longbow.png', weapon_category_id: 5, ammo_id: 4)
Weapon.create(name: 'センチネル', image: 'sentinel.png', weapon_category_id: 5, ammo_id: 4)
Weapon.create(name: 'クレーバー.50スナイパー', image: 'kraber.png', weapon_category_id: 5, ammo_id: 4)
Weapon.create(name: 'EVA-8オート', image: 'eva-8.png', weapon_category_id: 6, ammo_id: 5)
Weapon.create(name: 'モザンビークショットガン', image: 'mozambique.png', weapon_category_id: 6, ammo_id: 5)
Weapon.create(name: 'ピースキーパー', image: 'peacekeeper.png', weapon_category_id: 6, ammo_id: 5)
Weapon.create(name: 'マスティフショットガン', image: 'mastiff.png', weapon_category_id: 6, ammo_id: 5)
Weapon.create(name: 'P2020', image: 'p2020.png', weapon_category_id: 7, ammo_id: 1)
Weapon.create(name: 'RE-45オート', image: 're-45.png', weapon_category_id: 7, ammo_id: 1)
Weapon.create(name: 'ウィングマン', image: 'wingman.png', weapon_category_id: 7, ammo_id: 2)

Legend.create(name: 'ブラッドハウンド', image: 'bloodhound.png')
Legend.create(name: 'ジブラルタル', image: 'gibraltar.png')
Legend.create(name: 'ライフライン', image: 'lifeline.png')
Legend.create(name: 'パスファインダー', image: 'pathfinder.png')
Legend.create(name: 'レイス', image: 'wraith.png')
Legend.create(name: 'バンガロール', image: 'bangalore.png')
Legend.create(name: 'コースティック', image: 'caustic.png')
Legend.create(name: 'ミラージュ', image: 'mirage.png')
Legend.create(name: 'オクタン', image: 'octane.png')
Legend.create(name: 'ワットソン', image: 'wattson.png')
Legend.create(name: 'クリプト', image: 'crypto.png')
Legend.create(name: 'レヴナント', image: 'revenant.png')
Legend.create(name: 'ローバ', image: 'loba.png')
Legend.create(name: 'ランパート', image: 'rampart.png')
Legend.create(name: 'ホライゾン', image: 'horizon.png')
Legend.create(name: 'ヒューズ', image: 'fuse.png')
Legend.create(name: 'ヴァルキリー', image: 'valkyrie.png')
Legend.create(name: 'シア', image: 'seer.png')
Legend.create(name: 'アッシュ', image: 'ash.png')
Legend.create(name: 'マッドマギー', image: 'mad_maggie.png')
Legend.create(name: 'ニューキャッスル', image: 'newcastle.png')

Stage.create(name: 'KINGS CANYON', image: 'kings_canyon.png')
Stage.create(name: "WORLD'S EDGE", image: "world's_edge.png")
Stage.create(name: 'OLYMPUS', image: 'olympus.png')
Stage.create(name: 'STORM POINT', image: 'storm_point.png')

User.create(name: 'Sylpha', email: 'sylpha.games@gmail.com', password: 'password')
